export const windowsBaselineCases = [
    'packaged Windows app loads bundled Neovim with an isolated profile and Unicode paths',
    'Windows clipboard, AltGr events and queued input preserve saved text',
    'Windows branch switching ignores unrelated edits and protects edits in the target repository',
    'favorite workspaces support keyboard access, existing tabs, restart and missing folders',
    'keyboard-only workspace switching, editing, saving and dirty-close guard',
    'explorer commands create, rename, copy, move and recycle files from the keyboard',
    'completion opens on typing and Ctrl Space, accepts with Tab, and files show diagnostic counts',
    'Markdown preview renders unsaved edits and supports keyboard scrolling and dismissal',
    'relative line numbers update immediately and persist after restarting',
    'word wrap updates long lines immediately and persists after restarting',
    'font family and line height update the canvas and survive restarting',
    'settings can be navigated and changed entirely with the keyboard',
    'Git changes can be reviewed, staged and committed with the keyboard',
    'stage all keeps HEAD gutter marks until commit and preserves unsaved edits',
    'Problems can be selected, filtered, opened and cleared with the keyboard',
    'terminal toggle, focus, background execution and standalone terminal sessions',
    'references stay accessible after jumping and can be closed with the keyboard',
    'Rust debugger keyboard controls stop, inspect and step in the packaged app',
    'normal shutdown restores workspace order, active file and cursors',
    'window size and maximized state survive restart',
    'clicking editor glyphs moves the cursor, including wide text and detached pixel scrolling',
    'acrylic switches live without losing edits and persists across restarts',
    'upward touchpad gestures stop at the first row while replies are delayed',
    'cached editor text preserves its pixels at 100% scale',
    'cached editor text preserves its pixels at 125% scale',
    'cached editor text preserves its pixels at 150% scale'
] as const;
